# 觸發工作流的操作
on: push
# 工作流名字
name: Test, Build and Release apk
# 需要執行的任務
jobs:
  build:
    name: Build APK
    # 定義執行環境
    runs-on: ubuntu-latest
    # 執行步驟
    steps:
    # 步驟執行之前，先拉取最新程式碼
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # 配置 Flutter 環境
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.10.5'
    # 執行構建之前，更新 flutter 依賴
    - run: flutter pub get
    # 測試
    - run: flutter test
    - run: flutter build apk --debug --split-per-abi
    - name: Create a Release APK
      uses: ncipollo/release-action@v2
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.TOKEN }}